"use client";

import Link from "next/link";
import Image from "next/image";
import type { BusinessAdminSection } from "@/modules/business-admin/types/business-admin.types";
import { AdminModal } from "../components/AdminModal";
import { useBusinessWorkspace } from "../hooks/useBusinessWorkspace";

const navigation: [BusinessAdminSection, string][] = [["overview", "Resumen"], ["business", "Información y apariencia"], ["categories", "Categorías"], ["products", "Productos y servicios"], ["orders", "Pedidos"], ["team", "Equipo"], ["subscription", "Suscripción"]];
const nextStatus: Record<string, string | undefined> = { pending: "confirmed", confirmed: "in_progress", in_progress: "completed" };

export function BusinessWorkspacePage({ businessId }: { businessId: string }) {
  const workspace = useBusinessWorkspace(businessId);
  const { data } = workspace;
  if (workspace.isLoading || (!data && !workspace.error)) return <main className="admin-loading">Abriendo el negocio…</main>;
  if (!data) return <main className="workspace-error"><Link href="/admin">← Volver</Link><div className="admin-alert error">{workspace.error}</div></main>;

  const content = () => {
    if (workspace.section === "business" && workspace.businessDraft) return <section className="data-card"><div className="card-heading"><div><h2>Información y apariencia</h2><p>Datos públicos, contacto, logo, portada y publicación.</p></div></div><form className="admin-form" onSubmit={workspace.saveBusiness}><div className="form-grid"><label>Nombre<input required value={workspace.businessDraft.name} onChange={(e) => workspace.setBusinessDraft({ ...workspace.businessDraft!, name: e.target.value })} /></label><label>Tipo<input required value={workspace.businessDraft.business_type} onChange={(e) => workspace.setBusinessDraft({ ...workspace.businessDraft!, business_type: e.target.value })} /></label></div><label>Descripción<textarea rows={4} value={workspace.businessDraft.description} onChange={(e) => workspace.setBusinessDraft({ ...workspace.businessDraft!, description: e.target.value })} /></label><div className="form-grid"><label>Email de contacto<input type="email" value={workspace.businessDraft.contact_email} onChange={(e) => workspace.setBusinessDraft({ ...workspace.businessDraft!, contact_email: e.target.value })} /></label><label>Teléfono<input value={workspace.businessDraft.contact_phone} onChange={(e) => workspace.setBusinessDraft({ ...workspace.businessDraft!, contact_phone: e.target.value })} /></label></div><div className="form-grid"><label>Logo<input type="url" value={workspace.businessDraft.logo_url} onChange={(e) => workspace.setBusinessDraft({ ...workspace.businessDraft!, logo_url: e.target.value })} /></label><label>Imagen de portada<input type="url" value={workspace.businessDraft.hero_image_url} onChange={(e) => workspace.setBusinessDraft({ ...workspace.businessDraft!, hero_image_url: e.target.value })} /></label></div><label>Categoría de plataforma<select value={workspace.businessDraft.platform_category_id} onChange={(e) => workspace.setBusinessDraft({ ...workspace.businessDraft!, platform_category_id: e.target.value })}><option value="">Sin categoría</option>{data.platformCategories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="checkbox-label"><input checked={workspace.businessDraft.is_published} onChange={(e) => workspace.setBusinessDraft({ ...workspace.businessDraft!, is_published: e.target.checked })} type="checkbox" /> Publicar mi bisne</label><div className="form-footer"><button className="action-button" disabled={workspace.isSaving}>Guardar cambios</button></div></form></section>;
    if (workspace.section === "categories") return <section className="data-card"><div className="card-heading"><div><h2>Categorías del negocio</h2><p>Organiza el catálogo a tu manera.</p></div><button className="action-button" onClick={() => workspace.setModal("category")}>+ Nueva categoría</button></div><div className="management-grid">{data.categories.map((item) => <article className="management-card" key={item.id}><div><strong>{item.name}</strong><small>/{item.slug}</small></div><button className="danger-link" onClick={() => void workspace.deleteCategory(item.id)}>Eliminar</button></article>)}</div>{!data.categories.length ? <div className="empty-state">Todavía no hay categorías.</div> : null}</section>;
    if (workspace.section === "products") return <section className="data-card"><div className="card-heading"><div><h2>Productos y servicios</h2><p>Gestiona lo que ofrece el negocio.</p></div><button className="action-button" onClick={() => workspace.setModal("product")}>+ Nuevo producto</button></div><div className="management-grid">{data.products.map((item) => <article className="product-management-card" key={item.id}><div className="product-thumb">{item.image_url ? <Image alt="" height={52} src={item.image_url} unoptimized width={52} /> : item.name.slice(0, 1)}</div><div><strong>{item.name}</strong><span>{item.price} {item.currency}</span><small>{item.is_available ? "Disponible" : "No disponible"}</small></div><button className="danger-link" onClick={() => void workspace.deleteProduct(item.id)}>Archivar</button></article>)}</div>{!data.products.length ? <div className="empty-state">Todavía no hay productos ni servicios.</div> : null}</section>;
    if (workspace.section === "team") return <section className="data-card"><div className="card-heading"><div><h2>Equipo</h2><p>Personas con acceso a la administración.</p></div><button className="action-button" onClick={() => workspace.setModal("member")}>+ Añadir persona</button></div><div className="management-grid">{data.members.map((item) => <article className="management-card" key={item.id}><div><strong>{item.full_name}</strong><small>{item.email}</small></div><select value={item.role} onChange={(e) => void workspace.changeMemberRole(item.user_id, e.target.value)} disabled={item.role === "owner"}><option value="owner">Owner</option><option value="admin">Admin</option><option value="editor">Editor</option><option value="viewer">Viewer</option></select>{item.role !== "owner" ? <button className="danger-link" onClick={() => void workspace.removeMember(item.user_id)}>Quitar</button> : null}</article>)}</div></section>;
    if (workspace.section === "orders") return <section className="data-card"><div className="card-heading"><div><h2>Pedidos</h2><p>Seguimiento del trabajo del negocio.</p></div></div><div className="management-grid">{data.orders.map((item) => <article className="management-card" key={item.id}><div><strong>{item.order_number}</strong><small>{item.total} {item.currency}</small></div><span className="status-pill published">{item.status}</span>{nextStatus[item.status] ? <button onClick={() => void workspace.changeOrderStatus(item.id, nextStatus[item.status]!)}>Pasar a {nextStatus[item.status]}</button> : null}</article>)}</div>{!data.orders.length ? <div className="empty-state">No hay pedidos todavía.</div> : null}</section>;
    if (workspace.section === "subscription") return <section className="data-card"><div className="card-heading"><div><h2>Suscripción</h2><p>Pagos realizados a la plataforma.</p></div></div><div className="management-grid">{data.payments.map((item) => <article className="management-card" key={item.id}><div><strong>{item.transaction_number}</strong><small>{item.execution_date} → {item.expiration_date}</small></div><span className={`plan-pill ${item.plan}`}>{item.plan}</span><strong>{item.amount_paid}</strong></article>)}</div></section>;
    return <div className="section-stack"><div className="business-welcome"><div><p className="eyebrow">Tu negocio</p><h2>{data.business.name}</h2><p>{data.business.description ?? "Completa la información de tu bisne para comenzar."}</p></div>{data.business.site.logo_url ? <Image alt={`Logo de ${data.business.name}`} height={96} src={data.business.site.logo_url} unoptimized width={96} /> : <span>{data.business.name.slice(0, 1)}</span>}</div><div className="metric-grid"><article className="metric-card"><p>Visitas</p><strong>{data.analytics.visits}</strong><span>Al sitio público</span></article><article className="metric-card"><p>Pedidos</p><strong>{data.analytics.orders}</strong><span>{data.analytics.completed_orders} completados</span></article><article className="metric-card"><p>Conversión</p><strong>{data.analytics.conversion_rate}%</strong><span>{data.analytics.product_views} vistas de productos</span></article></div></div>;
  };

  return <main className={`business-admin-shell ${workspace.sidebarCollapsed ? "sidebar-collapsed" : ""}`}><button className={`sidebar-scrim ${workspace.menuOpen ? "visible" : ""}`} onClick={() => workspace.setMenuOpen(false)} /><aside className={`business-sidebar ${workspace.menuOpen ? "open" : ""}`}><div className="business-sidebar-brand"><button onClick={() => workspace.setMenuOpen(false)}>×</button><span>{data.business.name.slice(0, 1)}</span><div><strong>{data.business.name}</strong><small>Administración</small></div></div><button className="desktop-sidebar-collapse" onClick={() => workspace.setSidebarCollapsed(true)} type="button"><span>←</span> Ocultar menú</button><nav>{navigation.map(([id, label]) => <button className={workspace.section === id ? "active" : ""} key={id} onClick={() => workspace.navigate(id)}>{label}</button>)}</nav><Link href="/admin">← Panel de plataforma</Link><button onClick={workspace.logout}>Cerrar sesión</button></aside><section className="business-admin-content"><header className="business-admin-header"><button className="menu-button" onClick={() => workspace.setMenuOpen(true)}><span /><span /><span /></button><button aria-label={workspace.sidebarCollapsed ? "Mostrar barra lateral" : "Ocultar barra lateral"} className="desktop-sidebar-trigger" onClick={() => workspace.setSidebarCollapsed(!workspace.sidebarCollapsed)} type="button"><span /><span /><span /></button><div><p className="eyebrow">Administración del negocio</p><h1>{navigation.find(([id]) => id === workspace.section)?.[1]}</h1></div><Link className="visit-business-button" href={`/bisne/${data.business.slug}`} target="_blank">Visitar mi bisne</Link></header>{workspace.error ? <div className="admin-alert error">{workspace.error}</div> : null}{workspace.notice ? <div className="admin-alert success">{workspace.notice}</div> : null}{content()}</section>
  {workspace.modal === "category" ? <AdminModal title="Nueva categoría" subtitle="Crea una sección para organizar tus productos." onClose={() => workspace.setModal(null)}><form className="admin-form" onSubmit={workspace.createCategory}><label>Nombre<input required value={workspace.categoryDraft.name} onChange={(e) => workspace.setCategoryDraft({ ...workspace.categoryDraft, name: e.target.value })} /></label><label>Identificador web<input required value={workspace.categoryDraft.slug} onChange={(e) => workspace.setCategoryDraft({ ...workspace.categoryDraft, slug: e.target.value })} /></label><div className="form-footer"><button className="action-button">Crear categoría</button></div></form></AdminModal> : null}
  {workspace.modal === "member" ? <AdminModal title="Añadir al equipo" subtitle="El usuario debe tener una cuenta registrada." onClose={() => workspace.setModal(null)}><form className="admin-form" onSubmit={workspace.addMember}><label>Email<input required type="email" value={workspace.memberDraft.email} onChange={(e) => workspace.setMemberDraft({ ...workspace.memberDraft, email: e.target.value })} /></label><label>Rol<select value={workspace.memberDraft.role} onChange={(e) => workspace.setMemberDraft({ ...workspace.memberDraft, role: e.target.value as "admin" | "editor" | "viewer" })}><option value="admin">Admin</option><option value="editor">Editor</option><option value="viewer">Viewer</option></select></label><div className="form-footer"><button className="action-button">Añadir persona</button></div></form></AdminModal> : null}
  {workspace.modal === "product" ? <AdminModal title="Nuevo producto o servicio" subtitle="Añádelo al catálogo de tu bisne." onClose={() => workspace.setModal(null)}><form className="admin-form" onSubmit={workspace.createProduct}><div className="form-grid"><label>Nombre<input required value={workspace.productDraft.name} onChange={(e) => workspace.setProductDraft({ ...workspace.productDraft, name: e.target.value })} /></label><label>Identificador web<input required value={workspace.productDraft.slug} onChange={(e) => workspace.setProductDraft({ ...workspace.productDraft, slug: e.target.value })} /></label></div><div className="form-grid"><label>Tipo<select value={workspace.productDraft.product_type} onChange={(e) => workspace.setProductDraft({ ...workspace.productDraft, product_type: e.target.value as "product" | "service" })}><option value="product">Producto</option><option value="service">Servicio</option></select></label><label>Precio<input min="0" required step="0.01" type="number" value={workspace.productDraft.price} onChange={(e) => workspace.setProductDraft({ ...workspace.productDraft, price: e.target.value })} /></label></div><div className="form-grid"><label>Categoría interna<select value={workspace.productDraft.category_id} onChange={(e) => workspace.setProductDraft({ ...workspace.productDraft, category_id: e.target.value })}><option value="">Sin categoría</option>{data.categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Categoría de plataforma<select value={workspace.productDraft.platform_category_id} onChange={(e) => workspace.setProductDraft({ ...workspace.productDraft, platform_category_id: e.target.value })}><option value="">Sin categoría</option>{data.platformCategories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><label>Descripción<textarea value={workspace.productDraft.description} onChange={(e) => workspace.setProductDraft({ ...workspace.productDraft, description: e.target.value })} /></label><label>URL de imagen<input type="url" value={workspace.productDraft.image_url} onChange={(e) => workspace.setProductDraft({ ...workspace.productDraft, image_url: e.target.value })} /></label><label className="checkbox-label"><input checked={workspace.productDraft.is_published} onChange={(e) => workspace.setProductDraft({ ...workspace.productDraft, is_published: e.target.checked })} type="checkbox" /> Publicar al crear</label><div className="form-footer"><button className="action-button">Crear producto</button></div></form></AdminModal> : null}</main>;
}
