"use client";

import Image from "next/image";
import Link from "next/link";
import { usePlatformDiscovery } from "../hooks/usePlatformDiscovery";
import type { DiscoveryBusiness, DiscoveryProduct } from "../types/platform-public.types";

function BusinessCard({ business }: { business: DiscoveryBusiness }) {
  return <Link className="discovery-business-card" href={`/bisne/${business.slug}`}><div>{business.hero_image_url ? <Image alt={business.name} fill sizes="(max-width: 780px) 82vw, 390px" src={business.hero_image_url} unoptimized /> : <span>{business.name.slice(0, 1)}</span>}</div><section><small>{business.business_type}</small><h3>{business.name}</h3><p>{business.description ?? "Descubre todo lo que ofrece este bisne."}</p><strong>Visitar negocio →</strong></section></Link>;
}

function ProductCard({ product }: { product: DiscoveryProduct }) {
  return <Link className="discovery-product-card" href={`/bisne/${product.business_slug}/productos/${product.slug}`}><div>{product.image_url ? <Image alt={product.name} fill sizes="(max-width: 780px) 72vw, 290px" src={product.image_url} unoptimized /> : <span>{product.name.slice(0, 1)}</span>}</div><section><small>{product.business_name}</small><h3>{product.name}</h3><p>{product.description ?? "Consulta sus detalles."}</p><strong>{product.price} {product.currency}</strong></section></Link>;
}

export function PlatformHomePage() {
  const store = usePlatformDiscovery();
  return <main className="platform-public-page"><header className="platform-public-header"><Link href="/">El Bisne</Link><nav><a href="#explorar">Explorar</a><Link href="/login">Administrar mi bisne</Link></nav></header><section className="platform-hero"><p className="eyebrow">Todo el bisne, en un lugar</p><h1>Descubre lo que Cuba está creando.</h1><p>Negocios locales, productos únicos y nuevas formas de encontrarnos.</p><a href="#explorar">Comenzar a explorar ↓</a></section><section className="platform-discovery" id="explorar"><div className="discovery-heading"><div><p className="eyebrow">Explora El Bisne</p><h2>¿Qué estás buscando?</h2></div><div className="discovery-tabs" role="tablist"><button aria-selected={store.tab === "businesses"} className={store.tab === "businesses" ? "active" : ""} onClick={() => store.setTab("businesses")} role="tab">Negocios</button><button aria-selected={store.tab === "products"} className={store.tab === "products" ? "active" : ""} onClick={() => store.setTab("products")} role="tab">Productos</button></div></div><div className="discovery-filters"><label><span>Buscar por nombre</span><input placeholder={store.tab === "businesses" ? "Ej. Dulce Alma" : "Ej. Café latte"} type="search" value={store.search} onChange={(event) => store.setSearch(event.target.value)} /></label><label><span>Categoría</span><select value={store.categoryId} onChange={(event) => store.setCategoryId(event.target.value)}><option value="">Todas las categorías</option>{store.data?.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div>{store.error ? <div className="admin-alert error">{store.error}</div> : null}{store.isLoading ? <div className="discovery-loading">Buscando propuestas para ti…</div> : store.sections.length ? <div className="discovery-sections">{store.sections.map((section) => <section key={section.category.id}><div className="discovery-section-heading"><div><small>Categoría de la plataforma</small><h2>{section.category.name}</h2></div><span>{section.items.length} resultados</span></div><div className="discovery-slider">{store.tab === "businesses" ? (section.items as DiscoveryBusiness[]).map((business) => <BusinessCard business={business} key={business.id} />) : (section.items as DiscoveryProduct[]).map((product) => <ProductCard key={product.id} product={product} />)}</div></section>)}</div> : <div className="public-empty">No encontramos resultados con esos filtros.</div>}</section><section className="platform-cta"><p className="eyebrow">¿Tienes un negocio?</p><h2>Haz que más personas encuentren tu bisne.</h2><Link href="/login">Entrar a la administración</Link></section></main>;
}
