"use client";

import Image from "next/image";
import Link from "next/link";
import { DiscoverySlider } from "../components/DiscoverySlider";
import { usePlatformDiscovery } from "../hooks/usePlatformDiscovery";
import type { DiscoveryBusiness, DiscoveryProduct, DiscoveryService } from "../types/platform-public.types";

function BusinessLogo({ name, url }: { name: string; url: string | null }) { return <span aria-hidden="true" className="discovery-business-logo">{url ? <Image alt="" height={32} src={url} unoptimized width={32} /> : name.slice(0, 1)}</span>; }
function BusinessCard({ business }: { business: DiscoveryBusiness }) { return <Link className="discovery-business-card" href={`/bisne/${business.slug}`}><div>{business.hero_image_url ? <Image alt={business.name} fill sizes="(max-width: 780px) 82vw, 390px" src={business.hero_image_url} unoptimized /> : <span>{business.name.slice(0, 1)}</span>}<BusinessLogo name={business.name} url={business.logo_url} /></div><section><small>Negocio local</small><h3>{business.name}</h3><p>{business.description ?? "Descubre todo lo que ofrece este bisne."}</p><strong className="discovery-card-action">Visitar negocio <span>→</span></strong></section></Link>; }
function ProductCard({ product }: { product: DiscoveryProduct }) { const detailHref = `/bisne/${product.business_slug}/productos/${product.slug}`; return <article className="discovery-product-card"><Link aria-label={`Ver ${product.name}`} className="discovery-card-image" href={detailHref}>{product.image_url ? <Image alt={product.name} fill sizes="(max-width: 780px) 72vw, 290px" src={product.image_url} unoptimized /> : <span>{product.name.slice(0, 1)}</span>}</Link><section><div className="discovery-card-business"><BusinessLogo name={product.business_name} url={product.business_logo_url} /><small>{product.business_name}</small></div><Link className="discovery-card-title" href={detailHref}><h3>{product.name}</h3></Link><p>{product.description ?? "Consulta sus detalles."}</p><strong>{product.price} {product.currency}</strong><div className="discovery-product-actions"><Link href={detailHref}>Ver producto</Link><Link href={`/bisne/${product.business_slug}`}>Visitar negocio <span>→</span></Link></div></section></article>; }
function ServiceCard({ service }: { service: DiscoveryService }) { return <Link className="discovery-service-card" href={`/bisne/${service.business_slug}#servicios`}><div>{service.image_url ? <Image alt={service.name} fill sizes="(max-width: 780px) 82vw, 390px" src={service.image_url} unoptimized /> : <span>{service.name.slice(0, 1)}</span>}<b>Servicio</b></div><section><div className="discovery-card-business"><BusinessLogo name={service.business_name} url={service.business_logo_url} /><small>{service.business_name}</small></div><h3>{service.name}</h3><p>{service.description ?? "Conoce este servicio y conversa con el negocio."}</p><strong>{service.price ? `Desde ${service.price} ${service.currency}` : "Consultar detalles"}</strong><span className="discovery-card-action">Visitar negocio <i>→</i></span></section></Link>; }

export function PlatformHomePage() {
  const store = usePlatformDiscovery();
  return <main className="platform-public-page"><header className="platform-public-header"><Link href="/">El Bisne</Link></header><section className="platform-hero"><p className="eyebrow">Todo el bisne, en un lugar</p><h1>Descubre lo que Cuba está creando.</h1><p>Negocios locales, productos únicos, servicios profesionales y nuevas formas de encontrarnos.</p><a href="#explorar">Comenzar a explorar ↓</a></section><section className="platform-discovery" id="explorar"><div className="discovery-heading"><div><p className="eyebrow">Explora El Bisne</p><h2>¿Qué estás buscando?</h2></div><div className="discovery-tabs" role="tablist">{([['businesses','Negocios'],['products','Productos'],['services','Servicios']] as const).map(([id,label]) => <button aria-selected={store.tab === id} className={store.tab === id ? "active" : ""} key={id} onClick={() => store.setTab(id)} role="tab">{label}</button>)}</div></div><div className="discovery-filters"><label><span>Buscar por nombre</span><input placeholder={store.tab === "businesses" ? "Ej. Dulce Alma" : store.tab === "products" ? "Ej. Café latte" : "Ej. Fotografía"} type="search" value={store.search} onChange={(event) => store.setSearch(event.target.value)} /></label><label><span>Categoría</span><select value={store.categoryId} onChange={(event) => store.setCategoryId(event.target.value)}><option value="">Todas las categorías</option>{store.data?.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div>{store.error ? <div className="admin-alert error">{store.error}</div> : null}{store.isLoading ? <div className="discovery-loading">Buscando propuestas para ti…</div> : store.sections.length ? <div className="discovery-sections">{store.sections.map((section) => <section key={section.category.id}><div className="discovery-section-heading"><h2>{section.category.name}</h2></div><DiscoverySlider label={section.category.name}>{store.tab === "businesses" ? (section.items as DiscoveryBusiness[]).map((item) => <BusinessCard business={item} key={item.id} />) : store.tab === "products" ? (section.items as DiscoveryProduct[]).map((item) => <ProductCard key={item.id} product={item} />) : (section.items as DiscoveryService[]).map((item) => <ServiceCard key={item.id} service={item} />)}</DiscoverySlider></section>)}</div> : <div className="public-empty">No encontramos resultados con esos filtros.</div>}</section><section className="platform-cta"><p className="eyebrow">¿Tienes un negocio?</p><h2>Haz que más personas encuentren tu bisne.</h2><Link href="/login">Entrar a la administración</Link></section></main>;
  return <main className="platform-public-page"><header className="platform-public-header"><Link href="/">El Bisne</Link></header><section className="platform-hero"><p className="eyebrow">Todo el bisne, en un lugar</p><h1>Descubre lo que Cuba está creando.</h1><p>Negocios locales, productos únicos, servicios profesionales y nuevas formas de encontrarnos.</p><a href="#explorar">Comenzar a explorar ↓</a></section><section className="platform-discovery" id="explorar"><div className="discovery-heading"><div><p className="eyebrow">Explora El Bisne</p><h2>¿Qué estás buscando?</h2></div><div className="discovery-tabs" role="tablist">{([['businesses','Negocios'],['products','Productos'],['services','Servicios']] as const).map(([id,label]) => <button aria-selected={store.tab === id} className={store.tab === id ? "active" : ""} key={id} onClick={() => store.setTab(id)} role="tab">{label}</button>)}</div></div><div className="discovery-filters"><label><span>Buscar por nombre</span><input placeholder={store.tab === "businesses" ? "Ej. Dulce Alma" : store.tab === "products" ? "Ej. Café latte" : "Ej. Fotografía"} type="search" value={store.search} onChange={(event) => store.setSearch(event.target.value)} /></label><label><span>Categoría</span><select value={store.categoryId} onChange={(event) => store.setCategoryId(event.target.value)}><option value="">Todas las categorías</option>{store.data?.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label></div>{store.error ? <div className="admin-alert error">{store.error}</div> : null}{store.isLoading ? <div className="discovery-loading">Buscando propuestas para ti…</div> : store.sections.length ? <div className="discovery-sections">{store.sections.map((section) => <section key={section.category.id}><div className="discovery-section-heading"><h2>{section.category.name}</h2></div><DiscoverySlider label={section.category.name}>{store.tab === "businesses" ? (section.items as DiscoveryBusiness[]).map((item) => <BusinessCard business={item} key={item.id} />) : store.tab === "products" ? (section.items as DiscoveryProduct[]).map((item) => <ProductCard key={item.id} product={item} />) : (section.items as DiscoveryService[]).map((item) => <ServiceCard key={item.id} service={item} />)}</DiscoverySlider></section>)}</div> : <div className="public-empty">No encontramos resultados con esos filtros.</div>}</section><section className="platform-cta"><p className="eyebrow">¿Tienes un negocio?</p><h2>Haz que más personas encuentren tu bisne.</h2><Link href="/login">Entrar a la administración</Link></section></main>;
}
