import Link from "next/link";
import type { PlatformAdminData } from "../hooks/usePlatformAdminData";
import { AdminModal } from "./AdminModal";

export function BusinessesSection({ data }: { data: PlatformAdminData }) {
  const draft = data.businessDraft;
  const platformCategoryName = (id: string | null) =>
    data.platformCategories.find((category) => category.id === id)?.name ?? "Sin categoría";
  return (
    <section className="data-card">
      <div className="card-heading"><div><h2>Negocios</h2><p>Administra los negocios registrados en la plataforma.</p></div><button className="action-button" onClick={data.newBusiness} type="button">+ Nuevo negocio</button></div>
      <div className="search-toolbar"><span>{data.filteredBusinesses.length} negocio{data.filteredBusinesses.length === 1 ? "" : "s"}{data.businessSearch ? " encontrado(s)" : " registrado(s)"}</span><button className="secondary-button" onClick={data.openBusinessSearch} type="button">☷ Filtros{data.businessSearch ? " · 1" : ""}</button></div>
      {data.filteredBusinesses.length ? <div className="table-wrap"><table className="responsive-table compact-mobile-table"><thead><tr><th>Negocio</th><th>Categoría global</th><th>Tipo</th><th>Moneda</th><th>Estado</th><th>Contacto</th><th /></tr></thead><tbody>
        {data.filteredBusinesses.map((business) => <tr key={business.id}><td className="mobile-primary-cell" data-label="Negocio"><div className="entity-cell"><span>{business.name.slice(0, 1)}</span><div><strong>{business.name}</strong><small>/{business.slug}</small></div></div><details className="mobile-row-details"><summary>Ver más</summary><div className="mobile-detail-list"><p><span>Categoría</span><strong>{platformCategoryName(business.platform_category_id)}</strong></p><p><span>Venta online</span><strong>{business.sells_online ? "Activa" : "Inactiva"}</strong></p><p><span>Moneda</span><strong>{business.currency}</strong></p><p><span>Estado</span><strong>{business.is_published ? "Publicado" : "Borrador"}</strong></p><p><span>Contacto</span><strong>{business.contact_phone ?? business.contact_email ?? "—"}</strong></p></div><div className="mobile-detail-actions"><Link className="enter-business" href={`/admin/businesses/${business.id}`}>Entrar al negocio</Link><button className="danger" onClick={() => data.archiveBusiness(business)} type="button">Archivar</button></div></details></td><td data-label="Categoría">{platformCategoryName(business.platform_category_id)}</td><td data-label="Venta online">{business.sells_online ? "Activa" : "Inactiva"}</td><td data-label="Moneda">{business.currency}</td><td data-label="Estado"><span className={`status-pill ${business.is_published ? "published" : "draft"}`}>{business.is_published ? "Publicado" : "Borrador"}</span></td><td data-label="Contacto">{business.contact_phone ?? business.contact_email ?? "—"}</td><td data-label="Acciones"><div className="row-actions"><Link className="enter-business" href={`/admin/businesses/${business.id}`}>Entrar al negocio</Link><button className="danger" onClick={() => data.archiveBusiness(business)} type="button">Archivar</button></div></td></tr>)}
      </tbody></table></div> : <div className="empty-state">{data.businessSearch ? "No encontramos negocios que coincidan con la búsqueda." : "No hay negocios registrados."}</div>}

      {data.showBusinessForm ? <AdminModal title={data.editingBusinessId ? "Editar negocio" : "Crear negocio"} subtitle="Información comercial y configuración inicial." onClose={() => data.setShowBusinessForm(false)}><form className="admin-form" onSubmit={data.saveBusiness}>
        {!data.editingBusinessId ? <><p className="form-section-title">Cuenta del propietario</p><div className="form-grid"><label>Nombre completo<input required minLength={2} value={draft.owner_full_name} onChange={(e) => data.setBusinessDraft({ ...draft, owner_full_name: e.target.value })} /></label><label>Email del owner<input required type="email" value={draft.owner_email} onChange={(e) => data.setBusinessDraft({ ...draft, owner_email: e.target.value })} /></label></div><label>Contraseña inicial<input required minLength={8} type="password" value={draft.owner_password} onChange={(e) => data.setBusinessDraft({ ...draft, owner_password: e.target.value })} /></label><p className="form-section-title">Datos del negocio</p></> : null}
        <label>Nombre<input required minLength={2} value={draft.name} onChange={(e) => data.setBusinessDraft({ ...draft, name: e.target.value })} /></label><label className="checkbox-label"><input checked={draft.sells_online} onChange={(e) => data.setBusinessDraft({ ...draft, sells_online: e.target.checked })} type="checkbox" /> Vender online <small>Activa carrito y pedidos.</small></label>
        <label>Categoría reconocida por la plataforma<select value={draft.platform_category_id} onChange={(event) => data.setBusinessDraft({ ...draft, platform_category_id: event.target.value })}><option value="">Sin categoría global</option>{data.platformCategories.filter((category) => category.is_active || category.id === draft.platform_category_id).map((category) => <option key={category.id} value={category.id}>{category.name}{category.is_active ? "" : " (inactiva)"}</option>)}</select><small className="field-help">Es opcional y no sustituye las categorías internas del negocio.</small></label>
        {!data.editingBusinessId ? <div className="form-grid"><label>Identificador web<input required minLength={3} placeholder="Ej. cafe-central" value={draft.slug} onChange={(e) => data.setBusinessDraft({ ...draft, slug: e.target.value })} /><small className="field-help">Se usa en la dirección pública del negocio: /cafe-central.</small></label><label>Número de transacción<input required value={draft.transaction_number} onChange={(e) => data.setBusinessDraft({ ...draft, transaction_number: e.target.value })} /></label></div> : null}
        <label>Descripción<textarea rows={3} value={draft.description} onChange={(e) => data.setBusinessDraft({ ...draft, description: e.target.value })} /></label>
        <div className="form-grid"><label>Moneda<input required maxLength={3} value={draft.currency} onChange={(e) => data.setBusinessDraft({ ...draft, currency: e.target.value.toUpperCase() })} /></label><label>Zona horaria<input required value={draft.timezone} onChange={(e) => data.setBusinessDraft({ ...draft, timezone: e.target.value })} /></label></div>
        <div className="form-grid"><label>Email de contacto<input type="email" value={draft.contact_email} onChange={(e) => data.setBusinessDraft({ ...draft, contact_email: e.target.value })} /></label><label>Teléfono de contacto<input value={draft.contact_phone} onChange={(e) => data.setBusinessDraft({ ...draft, contact_phone: e.target.value })} /></label></div>
        <div className="form-grid"><label>URL del hero<input type="url" value={draft.hero_image_url} onChange={(e) => data.setBusinessDraft({ ...draft, hero_image_url: e.target.value })} /></label><label>URL del logo<input type="url" value={draft.logo_url} onChange={(e) => data.setBusinessDraft({ ...draft, logo_url: e.target.value })} /></label></div>
        {!data.editingBusinessId ? <><div className="form-grid"><label>Plan<select value={draft.plan} onChange={(e) => data.setBusinessDraft({ ...draft, plan: e.target.value as "basic" | "premium" })}><option value="basic">Básico</option><option value="premium">Premium</option></select></label><label>Teléfono que confirmó<input required value={draft.phone_number} onChange={(e) => data.setBusinessDraft({ ...draft, phone_number: e.target.value })} /></label></div><div className="form-grid"><label>Fecha de ejecución<input required type="date" value={draft.execution_date} onChange={(e) => data.setBusinessDraft({ ...draft, execution_date: e.target.value })} /></label><label>Fecha de expiración<input required min={draft.execution_date} type="date" value={draft.expiration_date} onChange={(e) => data.setBusinessDraft({ ...draft, expiration_date: e.target.value })} /></label></div><label>Monto pagado<input required min="0.01" step="0.01" type="number" value={draft.amount_paid} onChange={(e) => data.setBusinessDraft({ ...draft, amount_paid: e.target.value })} /></label></> : <label className="checkbox-label"><input type="checkbox" checked={draft.is_published} onChange={(e) => data.setBusinessDraft({ ...draft, is_published: e.target.checked })} /> Negocio publicado</label>}
        <div className="form-footer"><button className="secondary-button" onClick={() => data.setShowBusinessForm(false)} type="button">Cancelar</button><button className="action-button" disabled={data.isSaving} type="submit">{data.isSaving ? "Guardando…" : "Guardar negocio"}</button></div>
      </form></AdminModal> : null}
      {data.showBusinessSearch ? <AdminModal title="Filtros de negocios" subtitle="Configura las restricciones que debe cumplir el listado." onClose={() => data.setShowBusinessSearch(false)}><form className="admin-form" onSubmit={data.applyBusinessSearch}><label>Nombre, tipo o contacto<input autoFocus placeholder="Escribe una coincidencia…" type="search" value={data.businessSearchDraft} onChange={(event) => data.setBusinessSearchDraft(event.target.value)} /></label><div className="form-footer"><button className="secondary-button" onClick={data.clearBusinessSearch} type="button">Limpiar filtros</button><button className="action-button" type="submit">Aplicar filtros</button></div></form></AdminModal> : null}
    </section>
  );
}
