import type { PlatformAdminData } from "../hooks/usePlatformAdminData";
import { AdminModal } from "./AdminModal";

export function BusinessesSection({ data }: { data: PlatformAdminData }) {
  const draft = data.businessDraft;
  return (
    <section className="data-card">
      <div className="card-heading"><div><h2>Negocios</h2><p>Administra los negocios registrados en la plataforma.</p></div><button className="action-button" onClick={data.newBusiness} type="button">+ Nuevo negocio</button></div>
      {data.businesses.length ? <div className="table-wrap"><table><thead><tr><th>Negocio</th><th>Tipo</th><th>Moneda</th><th>Estado</th><th>Contacto</th><th /></tr></thead><tbody>
        {data.businesses.map((business) => <tr key={business.id}><td><div className="entity-cell"><span>{business.name.slice(0, 1)}</span><div><strong>{business.name}</strong><small>/{business.slug}</small></div></div></td><td>{business.business_type}</td><td>{business.currency}</td><td><span className={`status-pill ${business.is_published ? "published" : "draft"}`}>{business.is_published ? "Publicado" : "Borrador"}</span></td><td>{business.contact_phone ?? business.contact_email ?? "—"}</td><td><div className="row-actions"><button onClick={() => data.editBusiness(business)} type="button">Editar</button><button className="danger" onClick={() => data.archiveBusiness(business)} type="button">Archivar</button></div></td></tr>)}
      </tbody></table></div> : <div className="empty-state">No hay negocios registrados.</div>}

      {data.showBusinessForm ? <AdminModal title={data.editingBusinessId ? "Editar negocio" : "Crear negocio"} subtitle="Información comercial y configuración inicial." onClose={() => data.setShowBusinessForm(false)}><form className="admin-form" onSubmit={data.saveBusiness}>
        {!data.editingBusinessId ? <><p className="form-section-title">Cuenta del propietario</p><div className="form-grid"><label>Nombre completo<input required minLength={2} value={draft.owner_full_name} onChange={(e) => data.setBusinessDraft({ ...draft, owner_full_name: e.target.value })} /></label><label>Email del owner<input required type="email" value={draft.owner_email} onChange={(e) => data.setBusinessDraft({ ...draft, owner_email: e.target.value })} /></label></div><label>Contraseña inicial<input required minLength={8} type="password" value={draft.owner_password} onChange={(e) => data.setBusinessDraft({ ...draft, owner_password: e.target.value })} /></label><p className="form-section-title">Datos del negocio</p></> : null}
        <div className="form-grid"><label>Nombre<input required minLength={2} value={draft.name} onChange={(e) => data.setBusinessDraft({ ...draft, name: e.target.value })} /></label><label>Tipo de negocio<input required value={draft.business_type} onChange={(e) => data.setBusinessDraft({ ...draft, business_type: e.target.value })} /></label></div>
        {!data.editingBusinessId ? <div className="form-grid"><label>Slug<input required minLength={3} value={draft.slug} onChange={(e) => data.setBusinessDraft({ ...draft, slug: e.target.value })} /></label><label>Número de transacción<input required value={draft.transaction_number} onChange={(e) => data.setBusinessDraft({ ...draft, transaction_number: e.target.value })} /></label></div> : null}
        <label>Descripción<textarea rows={3} value={draft.description} onChange={(e) => data.setBusinessDraft({ ...draft, description: e.target.value })} /></label>
        <div className="form-grid"><label>Moneda<input required maxLength={3} value={draft.currency} onChange={(e) => data.setBusinessDraft({ ...draft, currency: e.target.value.toUpperCase() })} /></label><label>Zona horaria<input required value={draft.timezone} onChange={(e) => data.setBusinessDraft({ ...draft, timezone: e.target.value })} /></label></div>
        <div className="form-grid"><label>Email de contacto<input type="email" value={draft.contact_email} onChange={(e) => data.setBusinessDraft({ ...draft, contact_email: e.target.value })} /></label><label>Teléfono de contacto<input value={draft.contact_phone} onChange={(e) => data.setBusinessDraft({ ...draft, contact_phone: e.target.value })} /></label></div>
        <div className="form-grid"><label>URL del hero<input type="url" value={draft.hero_image_url} onChange={(e) => data.setBusinessDraft({ ...draft, hero_image_url: e.target.value })} /></label><label>URL del logo<input type="url" value={draft.logo_url} onChange={(e) => data.setBusinessDraft({ ...draft, logo_url: e.target.value })} /></label></div>
        {!data.editingBusinessId ? <div className="form-grid"><label>Plan<select value={draft.plan} onChange={(e) => data.setBusinessDraft({ ...draft, plan: e.target.value as "basic" | "premium" })}><option value="basic">Básico</option><option value="premium">Premium</option></select></label><label>Teléfono que confirmó<input required value={draft.phone_number} onChange={(e) => data.setBusinessDraft({ ...draft, phone_number: e.target.value })} /></label></div> : <label className="checkbox-label"><input type="checkbox" checked={draft.is_published} onChange={(e) => data.setBusinessDraft({ ...draft, is_published: e.target.checked })} /> Negocio publicado</label>}
        <div className="form-footer"><button className="secondary-button" onClick={() => data.setShowBusinessForm(false)} type="button">Cancelar</button><button className="action-button" disabled={data.isSaving} type="submit">{data.isSaving ? "Guardando…" : "Guardar negocio"}</button></div>
      </form></AdminModal> : null}
    </section>
  );
}
