import type { PlatformAdminData } from "../hooks/usePlatformAdminData";
import { AdminModal } from "./AdminModal";

export function PaymentsSection({ data }: { data: PlatformAdminData }) {
  const draft = data.paymentDraft;
  const businessName = (id: string) =>
    data.businesses.find((business) => business.id === id)?.name ?? "Negocio archivado";

  return (
    <section className="data-card">
      <div className="card-heading">
        <div><h2>Pagos de suscripción</h2><p>Historial de transferencias realizadas a la plataforma.</p></div>
        <div className="heading-actions"><button className="secondary-button" onClick={data.openPaymentFilters} type="button">☷ Filtros{data.activePaymentFilterCount ? ` · ${data.activePaymentFilterCount}` : ""}</button><button className="action-button" onClick={data.newPayment} type="button">+ Registrar pago</button></div>
      </div>
      <div className="search-toolbar"><span>{data.payments.length} pago{data.payments.length === 1 ? "" : "s"} mostrado{data.payments.length === 1 ? "" : "s"}</span>{data.activePaymentFilterCount ? <button onClick={() => void data.clearPaymentFilters()} type="button">Quitar filtros</button> : null}</div>
      {data.payments.length ? <div className="table-wrap"><table className="responsive-table compact-mobile-table"><thead><tr><th>Transacción</th><th>Negocio</th><th>Plan</th><th>Monto</th><th>Ejecución</th><th>Expiración</th><th>Teléfono</th><th /></tr></thead><tbody>
        {data.payments.map((payment) => <tr key={payment.id}><td className="strong-cell mobile-primary-cell" data-label="Transacción"><span className="desktop-cell-value">{payment.transaction_number}</span><div className="mobile-payment-summary"><strong>{payment.transaction_number}</strong><span>{businessName(payment.business_id)}</span><small>{new Intl.DateTimeFormat("es-CU", { timeZone: "UTC" }).format(new Date(`${payment.execution_date}T00:00:00Z`))}</small></div><details className="mobile-row-details"><summary>Ver más</summary><div className="mobile-detail-list"><p><span>Plan</span><strong>{payment.plan}</strong></p><p><span>Monto</span><strong>{payment.amount_paid}</strong></p><p><span>Expiración</span><strong>{new Intl.DateTimeFormat("es-CU", { timeZone: "UTC" }).format(new Date(`${payment.expiration_date}T00:00:00Z`))}</strong></p><p><span>Teléfono</span><strong>{payment.phone_number}</strong></p></div><div className="mobile-detail-actions"><button onClick={() => data.editPayment(payment)} type="button">Editar</button><button className="danger" onClick={() => data.deletePayment(payment)} type="button">Eliminar</button></div></details></td><td data-label="Negocio">{businessName(payment.business_id)}</td><td data-label="Plan"><span className={`plan-pill ${payment.plan}`}>{payment.plan}</span></td><td data-label="Monto">{payment.amount_paid}</td><td data-label="Ejecución">{new Intl.DateTimeFormat("es-CU", { timeZone: "UTC" }).format(new Date(`${payment.execution_date}T00:00:00Z`))}</td><td data-label="Expiración">{new Intl.DateTimeFormat("es-CU", { timeZone: "UTC" }).format(new Date(`${payment.expiration_date}T00:00:00Z`))}</td><td data-label="Teléfono">{payment.phone_number}</td><td data-label="Acciones"><div className="row-actions"><button onClick={() => data.editPayment(payment)} type="button">Editar</button><button className="danger" onClick={() => data.deletePayment(payment)} type="button">Eliminar</button></div></td></tr>)}
      </tbody></table></div> : <div className="empty-state">No hay pagos registrados.</div>}

      {data.showPaymentForm ? <AdminModal title={data.editingPaymentId ? "Editar pago" : "Registrar pago"} subtitle="La transacción debe ser única en toda la plataforma." onClose={() => data.setShowPaymentForm(false)}><form className="admin-form" onSubmit={data.savePayment}>
        <label>Negocio<select disabled={Boolean(data.editingPaymentId)} required value={draft.business_id} onChange={(e) => data.setPaymentDraft({ ...draft, business_id: e.target.value })}><option value="">Selecciona un negocio</option>{data.businesses.map((business) => <option key={business.id} value={business.id}>{business.name}</option>)}</select></label>
        <label>Número de transacción<input required value={draft.transaction_number} onChange={(e) => data.setPaymentDraft({ ...draft, transaction_number: e.target.value })} /></label>
        <div className="form-grid"><label>Plan<select value={draft.plan} onChange={(e) => data.setPaymentDraft({ ...draft, plan: e.target.value as "basic" | "premium" })}><option value="basic">Básico</option><option value="premium">Premium</option></select></label><label>Teléfono que confirmó<input required value={draft.phone_number} onChange={(e) => data.setPaymentDraft({ ...draft, phone_number: e.target.value })} /></label></div>
        <div className="form-grid"><label>Fecha de ejecución<input required type="date" value={draft.execution_date} onChange={(e) => data.setPaymentDraft({ ...draft, execution_date: e.target.value })} /></label><label>Fecha de expiración<input required min={draft.execution_date} type="date" value={draft.expiration_date} onChange={(e) => data.setPaymentDraft({ ...draft, expiration_date: e.target.value })} /></label></div>
        <label>Monto pagado<input required min="0.01" step="0.01" type="number" value={draft.amount_paid} onChange={(e) => data.setPaymentDraft({ ...draft, amount_paid: e.target.value })} /></label>
        <div className="form-footer"><button className="secondary-button" onClick={() => data.setShowPaymentForm(false)} type="button">Cancelar</button><button className="action-button" disabled={data.isSaving} type="submit">{data.isSaving ? "Guardando…" : "Guardar pago"}</button></div>
      </form></AdminModal> : null}
      {data.showPaymentFilters ? <AdminModal title="Filtros de suscripciones" subtitle="Configura únicamente las restricciones que necesites." onClose={() => data.setShowPaymentFilters(false)}><form className="admin-form filter-modal-form" onSubmit={data.searchPayments}>
        <div className="form-grid"><label>Negocio<input placeholder="Coincidencia por nombre" value={data.paymentFilterDraft.business_name} onChange={(event) => data.setPaymentFilterDraft({ ...data.paymentFilterDraft, business_name: event.target.value })} /></label><label>Transacción<input placeholder="Número o parte" value={data.paymentFilterDraft.transaction_number} onChange={(event) => data.setPaymentFilterDraft({ ...data.paymentFilterDraft, transaction_number: event.target.value })} /></label></div>
        <div className="form-grid"><label>Plan<select value={data.paymentFilterDraft.plan} onChange={(event) => data.setPaymentFilterDraft({ ...data.paymentFilterDraft, plan: event.target.value as "" | "basic" | "premium" })}><option value="">Todos</option><option value="basic">Básico</option><option value="premium">Premium</option></select></label><label>Teléfono<input placeholder="Número o parte" value={data.paymentFilterDraft.phone_number} onChange={(event) => data.setPaymentFilterDraft({ ...data.paymentFilterDraft, phone_number: event.target.value })} /></label></div>
        <p className="form-section-title">Fechas y monto</p><div className="form-grid"><label>Fecha de ejecución<input type="date" value={data.paymentFilterDraft.execution_date} onChange={(event) => data.setPaymentFilterDraft({ ...data.paymentFilterDraft, execution_date: event.target.value })} /></label><label>Fecha de expiración<input type="date" value={data.paymentFilterDraft.expiration_date} onChange={(event) => data.setPaymentFilterDraft({ ...data.paymentFilterDraft, expiration_date: event.target.value })} /></label></div>
        <div className="form-grid"><label>Monto pagado<input min="0" step="0.01" type="number" value={data.paymentFilterDraft.amount_paid} onChange={(event) => data.setPaymentFilterDraft({ ...data.paymentFilterDraft, amount_paid: event.target.value })} /></label><label>Creado exactamente<input type="datetime-local" value={data.paymentFilterDraft.created_at} onChange={(event) => data.setPaymentFilterDraft({ ...data.paymentFilterDraft, created_at: event.target.value })} /></label></div>
        <p className="form-section-title">Identificadores exactos</p><div className="form-grid"><label>ID del pago<input placeholder="UUID" value={data.paymentFilterDraft.payment_id} onChange={(event) => data.setPaymentFilterDraft({ ...data.paymentFilterDraft, payment_id: event.target.value })} /></label><label>ID del negocio<input placeholder="UUID" value={data.paymentFilterDraft.business_id} onChange={(event) => data.setPaymentFilterDraft({ ...data.paymentFilterDraft, business_id: event.target.value })} /></label></div>
        <div className="form-footer sticky-form-footer"><button className="secondary-button" onClick={() => void data.clearPaymentFilters()} type="button">Limpiar filtros</button><button className="action-button" type="submit">Aplicar filtros</button></div>
      </form></AdminModal> : null}
    </section>
  );
}
