"use client";

import Image from "next/image";
import Link from "next/link";
import { useCheckout } from "../hooks/useCheckout";
import { usePublicBusiness } from "../hooks/usePublicBusiness";
import { BusinessMaintenance } from "../components/BusinessMaintenance";

export function CartPage({ slug }: { slug: string }) {
  const store = usePublicBusiness(slug);
  const checkout = useCheckout(slug, { name: store.data?.business.name ?? "", phone: store.data?.business.contact_phone ?? null }, store.cart, store.clear);
  if (!store.data) return <main className="public-loading">{store.error ?? "Cargando carrito…"}</main>;
  if (!store.data.business.is_published) return <BusinessMaintenance name={store.data.business.name} />;
  if (!store.data.business.sells_online) return <main className="public-loading"><Link href={`/bisne/${slug}`}>Este negocio no recibe pedidos online. Volver al catálogo.</Link></main>;
  if (checkout.orderNumber) return <main className="order-success"><span>✓</span><h1>Pedido enviado</h1><p>Tu número de pedido es <strong>{checkout.orderNumber}</strong>.</p>{checkout.whatsAppUrl ? <a href={checkout.whatsAppUrl} rel="noreferrer" target="_blank">Enviar pedido por WhatsApp</a> : <p>El pedido quedó guardado, pero el negocio no tiene un número de WhatsApp configurado.</p>}<Link href={`/bisne/${slug}`}>Volver a {store.data.business.name}</Link></main>;
  return <main className="cart-page"><header><Link href={`/bisne/${slug}`}>← Seguir viendo productos</Link><span>{store.data.business.name}</span></header><div className="cart-layout"><section><p className="eyebrow">Tu selección</p><h1>Carrito</h1>{store.cart.map((item) => <article className="cart-item" key={item.product.id}><div>{item.product.image_url ? <Image alt="" fill sizes="72px" src={item.product.image_url} unoptimized /> : item.product.name.slice(0, 1)}</div><section><strong>{item.product.name}</strong><small>{item.product.price} {item.product.currency}</small></section><div className="quantity-control"><button onClick={() => store.setQuantity(item.product.id, item.quantity - 1)}>−</button><span>{item.quantity}</span><button onClick={() => store.setQuantity(item.product.id, item.quantity + 1)}>+</button></div></article>)}{!store.cart.length ? <div className="public-empty">Tu carrito está vacío.</div> : null}<div className="cart-total"><span>Total</span><strong>{store.total.toFixed(2)} {store.cart[0]?.product.currency ?? ""}</strong></div></section><section className="checkout-card"><h2>Enviar pedido</h2><p>Déjanos tus datos para que el negocio pueda contactarte.</p><form onSubmit={checkout.submit}><label>Nombre completo<input minLength={2} required value={checkout.customer.customer_name} onChange={(e) => checkout.setCustomer({ ...checkout.customer, customer_name: e.target.value })} /></label><label>Email<input type="email" value={checkout.customer.customer_email} onChange={(e) => checkout.setCustomer({ ...checkout.customer, customer_email: e.target.value })} /></label><label>Teléfono<input minLength={3} value={checkout.customer.customer_phone} onChange={(e) => checkout.setCustomer({ ...checkout.customer, customer_phone: e.target.value })} /></label><label>Notas para el negocio<textarea maxLength={2000} rows={4} value={checkout.customer.notes} onChange={(e) => checkout.setCustomer({ ...checkout.customer, notes: e.target.value })} /></label>{checkout.error ? <div aria-live="assertive" className="form-error checkout-error" role="alert">{checkout.error}</div> : <p className="checkout-help">Indica al menos un email o un teléfono para que el negocio pueda contactarte.</p>}<button disabled={checkout.isSending || !store.cart.length}>{checkout.isSending ? "Enviando…" : "Enviar pedido"}</button></form></section></div></main>;
}
